default_context:
  project_name: 'Example Full Stack FastAPI Application with PostgreSQL'
  project_slug: 'example-full-stack-fastapi-application-with-postgresql'
  domain_main: 'example-full-stack-fastapi-application-with-postgresql.com'
  domain_staging: 'stag.example-full-stack-fastapi-application-with-postgresql.com'
  docker_swarm_stack_name_main: 'example-full-stack-fastapi-application-with-postgresql-com'
  docker_swarm_stack_name_staging: 'stag-example-full-stack-fastapi-application-with-postgresql-com'
  secret_key: 'my_secret_key'
  first_superuser: 'admin@example-full-stack-fastapi-application-with-postgresql.com'
  first_superuser_password: 'password'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.example-full-stack-fastapi-application-with-postgresql.com", "https://stag.example-full-stack-fastapi-application-with-postgresql.com", "https://example-full-stack-fastapi-application-with-postgresql.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@example-full-stack-fastapi-application-with-postgresql.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@example-full-stack-fastapi-application-with-postgresql.com'
  pgadmin_default_user_password: 'password'
  traefik_constraint_tag: 'example-full-stack-fastapi-application-with-postgresql.com'
  traefik_constraint_tag_staging: 'stag.example-full-stack-fastapi-application-with-postgresql.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
